### ISSUE TITLE
Different transitions for different screens

### ISSUE THREAD

**Issue by Sterlingryan** [plmok61/react-navigation-transitions#1]
Hi,

Thank you for the work you have been putting into this, it works awesomely. I would like to ask you if there is a way to do different transitions for different screens. For example I would like that a screen 'About' is accessed by swiping to the right (i.e fromRight), and the user can get back to the 'Welcome' screen by swiping to the left (i.e fromLeft). Excuse my inexperience in react, but is there a way where I could do that ?

**Comment by plmok61** [comment]
Sorry for taking so long to respond. As far as I know, you can't do it by using the transitionConfig. This is probably my biggest complaint with React Navigation.
