### ISSUE TITLE
SafeAreaView doesn't work with this library

### ISSUE THREAD

**Issue by alisherakb** [plmok61/react-navigation-transitions#11]
Hi,

I'm using  `SafeAreaView` from `react-navigation` and when I'm trying to add custom transition using this library the `SafeAreaView` is not taking into account on iOS devices.

Please help.

**Comment by plmok61** [comment]
@alisherakb Can you please be a little more specific about what is exactly not working? Adding a screenshot would be helpful.

**Comment by alisherakb** [comment]
@plmok61 
Here is my code:
```
import { SafeAreaView } from 'react-navigation';

<SafeAreaView style={{ flex: 1 }}>
   <View />
</SafeAreaView>
```
SafeAreaView sets automatic margins to container in order to properly show content on all devices. 

But when I'm using this library, this component doesn't work and thus margins is not set. 
Here is the pics:
![customtransition](https://user-images.githubusercontent.com/26904008/51698067-fa74c400-2011-11e9-98dd-069d42fa0d23.jpg)

![nocustomtransition](https://user-images.githubusercontent.com/26904008/51698084-03fe2c00-2012-11e9-9288-0e77b1f53869.jpg)

**Comment by plmok61** [comment]
@alisherakb I believe this might be an issue with `react-navigation` itself. Is this the same issue?
https://github.com/react-navigation/react-navigation/issues/3055

If so, try using forceInset. You can read about it here:
https://reactnavigation.org/docs/en/handling-iphonex.html

Please let me know if this fixes the issue and I will add an example to the README.

**Comment by alisherakb** [comment]
@plmok61  
The issue is not the same. Because SafeAreaView works perfectly if I remove this line `transitionConfig: (nav) => handleCustomTransition(nav)`

I also tried to set:
`<SafeAreaView forceInset={'always'}>`
But it doesn't work...

Any ideas what can cause a problem using the custom transition?

**Comment by plmok61** [comment]
I will have to play around with this tonight and possibly over the weekend. Thanks for opening this issue.

**Comment by alisherakb** [comment]
@plmok61 I would be very grateful. Looking forward.

**Comment by plmok61** [comment]
@alisherakb can you show me your `navigationOptions` for this screen in the photo and `StackNavigatorConfig `?

**Comment by plmok61** [comment]
@alisherakb I might have figured it out. 

Instead of: `forceInset={'always'}`

Try: `forceInset={{ top: 'always', bottom: 'always' }}`

**Comment by alisherakb** [comment]
> forceInset={{ top: 'always', bottom: 'always' }}

Thank you very much! You saved me.

**Comment by plmok61** [comment]
Re-opening so I remember to add an example to the README for how to deal with this since `react-navigation` doesn't seem to explain it well.
