### ISSUE TITLE
not working for stackactions reset dispatch

### ISSUE THREAD

**Issue by Taymindis** [plmok61/react-navigation-transitions#13]

**Comment by plmok61** [comment]
Can you provide some more details, please?

**Comment by sisimogangg** [comment]
@Taymindis reporting an issue is considered a very helpful thing in open source. I'd advise you to include more details next time. Otherwise I think this can be closed.

**Comment by lorenc-tomasz** [comment]
I guess that he want to have possibility to see transitions while the stack is reseted. By as far I know there is no possibulity to show animation / transition using react-navigation with reset action. 

Example:

>>>const resetAction = StackActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'Profile' })],
});
this.props.navigation.dispatch(resetAction);

It would be nice to see the transition here, but... :( I guess it's note for react-navigation guys.

**Comment by plmok61** [comment]
Closing because this is an issue with react-navigation. You can read about it [here](https://github.com/react-navigation/stack/issues/139)
