### ISSUE TITLE
zoomIn() not working correctly with back navigation on Android

### ISSUE THREAD

**Issue by dsgoers** [plmok61/react-navigation-transitions#14]
Hello!  Thanks for creating this library.  I'm using `zoomIn(1000)` as my `transitionConfig` and when I call `NavigationActions.back()` the previous screen "flashes" during the transition.  Please see attached files and let me know if you need more info.
![untitled](https://user-images.githubusercontent.com/8580520/52865890-92deff80-310b-11e9-8d6f-aeffec73cd3c.gif)

**Comment by plmok61** [comment]
@dsgoers I will take a look at this over the weekend

**Comment by jekingohel** [comment]
Same issue.
How to resolve this issue?

**Comment by plmok61** [comment]
Just wanted to give you an update. I am working on getting an Android test device. The Android simulator doesn't like running on my Mac. Sorry for the delay!

**Comment by csgonutty** [comment]
Having exactly the same issue. Thanks for updating us @plmok61

**Comment by birdgg** [comment]
from code here https://github.com/fram-x/FluidTransitions/blob/develop/lib/Transitions/getScaleTransitions.js

I set startScale to 0.005 fix this problem

**Comment by plmok61** [comment]
I will make this update tonight after work and test it out on iOS. If it looks good, I will push the change up and somebody with an Android can confirm that it fixes the back button issue.

**Comment by plmok61** [comment]
@dsgoers @csgonutty @birdgg @jekingohel The update has been pushed up. Please let me know if this resolve the issue.

**Comment by dsgoers** [comment]
Looks great, thanks!
