### ISSUE TITLE
How to add this between just 2 screens

### ISSUE THREAD

**Issue by imjaadH** [plmok61/react-navigation-transitions#2]
I want to go from screen A to screen B while using some transition..How can i achieve that..
Thanks a lot

**Comment by plmok61** [comment]
If we have screens A, B, and C, you only want to transition to work from screen A to B? Is this correct?

**Comment by alexcittadini** [comment]
I'd like to know this too. The example sets global transitions. How do you set different transitions for specific screen to screen navigation?

**Comment by HerrX2000** [comment]
+1

**Comment by CarrieKami** [comment]
Hey... is it possible to set the transitions for specific screens and not just globally, as previously asked?

**Comment by imjaadH** [comment]
I dont think its possible with this library, you have to create separate
stack for those screens

*--Electronically Yours,*

**Comment by seblambla** [comment]
Hi, you can actually do it as follows. Let's consider I want to have a zoom-in transition only between the country selection screen and the language selection screen:

```
import { zoomIn } from 'react-navigation-transitions'

const handleCustomTransition = ({ scenes }) => {
 const prevScene = scenes[scenes.length - 2],
   nextScene = scenes[scenes.length - 1]

  // Custom transitions go there
  if (prevScene 
    && prevScene.route.routeName === 'CountryScreen' 
    && nextScene.route.routeName === 'LanguageScreen') {
    return zoomIn()
  }
}

const PrimaryNav = createStackNavigator({
  CountryScreen: { screen: CountryScreen },
  LanguageScreen: { screen: LanguageScreen }
}, {
  transitionConfig: (nav) => handleCustomTransition(nav)
})
```

**Comment by MustaphaBounoua** [comment]
> Hi, you can actually do it as follows. Let's consider I want to have a zoom-in transition only between the country selection screen and the language selection screen:
> 
> ```
> const handleCustomTransition = ({scenes}) => {
>  const prevScene = scenes[scenes.length - 2],
>    currentScene = scenes[scenes.length - 1]
> 
>   // Custom transitions go there
>   if (prevScene 
>     && prevScene.route.routeName === 'CountryScreen' 
>     && currentScene.route.routeName === 'LanguageScreen') {
>     return zoomIn()
>   }
> }
> 
> const PrimaryNav = createStackNavigator({
>   CountryScreen: { screen: CountryScreen },
>   LanguageScreen: { screen: LanguageScreen }
> }, {
>   transitionConfig: (scenes) => handleCustomTransition(scenes)
> })
> ```

the variable scenes how you get it?

**Comment by seblambla** [comment]
@MustaphaBounoua hi, the `scenes` variable comes from transitionConfig (have a look at my `createStackNavigator` function)

**Comment by MustaphaBounoua** [comment]
@SebLambla , Yes , It works perfectly , thanks men it's genius :D

**Comment by plmok61** [comment]
@SebLambla this is great. When I get some time I will add your example to the README and credit you.

**Comment by seblambla** [comment]
@plmok61 I think it's a good idea as this use case can be useful given the current Github issues list ;). I've renamed some variables in order to be easier to understand. This piece of code as been written with the help of [this post](https://github.com/plmok61/react-navigation-transitions/issues/5#issuecomment-429235697).

**Comment by plmok61** [comment]
The example has been added. I'm surprised the react-navigation docs don't have an example like this.
