### ISSUE TITLE
dont animaiton in splash screen

### ISSUE THREAD

**Issue by psobhanlo** [plmok61/react-navigation-transitions#20]
hi when add transtion in splash screen next home page screen with
`this.props.navigation.replace('Login')`
not work. but only work in 
`this.props.navigation.push('Login')`

**Comment by plmok61** [comment]
This is an issue with react-navigation itself. `replace` and `reset` do not worth with animations. You can read more [here](https://github.com/react-navigation/stack/issues/139)
