### ISSUE TITLE
doesn't affect createSwitchNavigator?

### ISSUE THREAD

**Issue by vinurs** [plmok61/react-navigation-transitions#24]
hello, i use it with createSwitchNavigator, but it doesn't work, but works with others like createSwitchNavigator

**Comment by plmok61** [comment]
I have personally never used a SwitchNavigator but after taking a look at the docs, here is what I have found. The `SwitchNavigatorConfig ` does not have a key for `transitionConfig`. This means you cannot use custom transitions with this navigator. See the docs [here](https://reactnavigation.org/docs/en/switch-navigator.html)


If you want to use custom transitions, use the StackNavigator. The `StackNavigatorConfig` does have a `transitionConfig` key. See the docs [here](https://reactnavigation.org/docs/en/stack-navigator.html#routeconfigs)
