### ISSUE TITLE
More transitions

### ISSUE THREAD

**Issue by AppLetico** [plmok61/react-navigation-transitions#8]
This is nice.  Looking for: fromRight, fromBottom

**Comment by alz10** [comment]
im waiting for this too

**Comment by plmok61** [comment]
@jjg77 and @Albert0405 by default transition animations with react-navigation slide in from the right. You can also set the mode to 'modal' to have the screens slide in from the bottom. Is there anything else you would suggest?

**Comment by plmok61** [comment]
Actually, I just realized that android is different. I will add fromRight and fromBottom
